# From https://github.com/craigcitro/r-travis
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - "./travis-tool.sh github_package"
  - ./travis-tool.sh install_deps
script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  slack: ropensci:wh30e1MP9Am3wXb2wJx1ZRFi
  email:
    on_success: change
    on_failure: always

github_packages:
  - devtools
  - testthat
  - lmullen/gender-data-pkg
